import os
import json
import re

def sync():
    root_dir = "."
    assets = []

    # Find all metadata.json files
    for root, dirs, files in os.walk(root_dir):
        if "metadata.json" in files:
            path = os.path.join(root, "metadata.json")
            with open(path, 'r') as f:
                try:
                    data = json.load(f)
                    data['relative_path'] = os.path.relpath(root, root_dir)
                    assets.append(data)
                except Exception as e:
                    print(f"Error reading {path}: {e}")

    # Sort assets by category and name
    assets.sort(key=lambda x: (x.get('category', ''), x.get('asset_name', '')))

    # Group by category
    categories = {}
    for asset in assets:
        cat = asset.get('category', 'Uncategorized')
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(asset)

    # 1. Update ASSET_CATALOG.md
    catalog_content = "# Centralized Asset Catalog\n\nThis catalog provides a high-level overview of all strategic assets available in the agentdit- repository. Each asset is designed to be a reusable, high-leverage component for future monetization and scaling.\n\n"

    # Mapping for numbered sections if possible, or just use category names
    category_map = {
        "arabic-ai": "Arabic AI",
        "quant-finance": "Quant Finance",
        "llm-engineering": "LLM Engineering",
        "ai-automation": "AI Automation",
        "computer-vision": "Computer Vision",
        "scientific-ai": "Scientific AI",
        "hidden-value-discovery": "Hidden Value Discovery",
        "dataset-businesses": "Dataset Businesses",
        "open-source-products": "Open Source Products",
        "high-leverage-research": "High Leverage Research"
    }

    for i, (cat_key, cat_name) in enumerate(category_map.items(), 1):
        catalog_content += f"## {i}. {cat_name}\n"
        if cat_key in categories:
            for asset in categories[cat_key]:
                name = asset.get('asset_name', 'Unnamed Asset')
                path = asset.get('relative_path')
                moat = ""
                # Try to extract moat from README.md if it exists
                readme_path = os.path.join(path, "README.md")
                if os.path.exists(readme_path):
                    with open(readme_path, 'r') as f:
                        content = f.read()
                        match = re.search(r"\*\*Moat\*\*: (.*)", content)
                        if match:
                            moat = match.group(1).strip()

                catalog_content += f"- **[{name}](./{path})**\n"
                if moat:
                    catalog_content += f"  - **Moat**: {moat}\n"
                catalog_content += f"  - **Contributor**: [Jules-Alpha-Architect (jules-agent)](./agents/jules.json)\n"
        else:
            catalog_content += "*No assets yet.*\n"
        catalog_content += "\n"

    catalog_content += "---\n*Generated by the Agent Asset Discovery System.*\n"

    with open("ASSET_CATALOG.md", 'w') as f:
        f.write(catalog_content)
    print("ASSET_CATALOG.md updated.")

    # 2. Update agents/jules.json
    jules_path = "agents/jules.json"
    if os.path.exists(jules_path):
        with open(jules_path, 'r') as f:
            jules_data = json.load(f)

        jules_data['contributed_assets'] = sorted(list(set([a['relative_path'] for a in assets])))
        jules_data['contribution_count'] = len(jules_data['contributed_assets'])

        with open(jules_path, 'w') as f:
            json.dump(jules_data, f, indent=2)
        print("agents/jules.json updated.")

if __name__ == "__main__":
    sync()
